### ISSUE TITLE
AttributeError with Munki 3.3.0.3515

### ISSUE THREAD

**Issue by delbertcole** [clburlison/scripts#8]
Script was perviously working under Munki 2. Now I receive the following error when trying to run against my latest Munki instance:

> Traceback (most recent call last):
>   File "munkiimport_logic_audio.py", line 205, in <module>
>     main()
>   File "munkiimport_logic_audio.py", line 147, in main
>     munkiimport.repoAvailable = munkiimport.repo_available
> AttributeError: 'module' object has no attribute 'repo_available'

Is there any plan to resolve this issue? Can you recommend a work-a-around?

Thank you for your time,
DC

**Comment by clburlison** [comment]
I currently have no plans to resolve this error however I would accept a pull request to update the code to support munki 3.

As a work around you can install the munki 2 code base and then run this script.

**Comment by delbertcole** [comment]
Can I run the Munki 2 code based on the same server that is running Munki 3? Sorry for the questions, I am fairly new to this platform. Thank you for your time.

**Comment by delbertcole** [comment]
Thank you. Your work around solves my problem.

Take care,
DC
